spring.application.name=API-login


### ---- Fonte de dados H2 (modo arquivo) ----
spring.datasource.url=jdbc:h2:file:./data/dbsebrea
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

### ---- JPA/Hibernate: criar/atualizar tabelas automaticamente ----
# "update" cria/atualiza o esquema sem apagar dados
# (use "create-drop" ou "create" somente em dev se quiser recriar tudo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

### ---- H2 Console ----
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
